--- 
title: "National Health and Nutrition Examination Survey Visualization"
author: "Daniel Young (day2127), Ruijie Zhang (rz2596), Shubham Kaushal (sk5118)"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

We decided to take a look at the relationships in the National Health and Nutrition Examination Survey conducted by the CDC. It is "a program of studies designed to assess the health and nutritional status of adults and children in the United States". We find it is unique because it: "combines interviews and physical examinations". This allows us to look at objective trends like height and weight as well as data from personal experience like smoking and depression, as well as combining the two to see if one has impact on the other. The data NHANES offers is expansive and we had to look carefully for bits and pieces we wanted to examine because there were so many variables to sift through. We eventually decided on questioning some "common sense" ideas we had in order to see if they actually had grounding in real-world data. For example, we ask things like: do people who work more drink more coffee, do people who started smoking earlier have stunted growth, does income really affect nutrition that much, do people really "let themselves go" once they are married and older, and many more. In the end, we were able to find evidence of some of these "common sense" ideas whereas for others we could not find anything meaningful.